// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {model} from '../models';
import {main} from '../models';
import {update} from '../models';
import {devsync} from '../models';

export function AddBookmark(arg1:model.GallerySummary):Promise<model.Bookmark>;

export function AddBookmarkFromURL(arg1:string):Promise<model.Bookmark>;

export function AddHistory(arg1:model.GallerySummary,arg2:string):Promise<void>;

export function AddLocalDir(arg1:string):Promise<string>;

export function AddPlugin(arg1:string):Promise<main.PluginInfo>;

export function AddToSeries(arg1:string,arg2:Array<string>):Promise<model.Series>;

export function AppVersion():Promise<string>;

export function ApplyFileNameFormat():Promise<number>;

export function BookmarkRange(arg1:model.RangeRequest):Promise<model.Bookmark>;

export function Bookmarks():Promise<Array<model.Bookmark>>;

export function CancelViewerLoads(arg1:string):Promise<void>;

export function CandidateFromURL(arg1:string):Promise<model.CreatorCandidate>;

export function CheckUpdate():Promise<update.Release>;

export function ChooseSiteDir(arg1:string,arg2:string):Promise<string>;

export function ClearCustomThumb(arg1:string):Promise<model.Bookmark>;

export function ClearHistory():Promise<void>;

export function ClipboardText():Promise<string>;

export function CreateSeries(arg1:string,arg2:Array<string>):Promise<model.Series>;

export function DeleteDownload(arg1:string):Promise<void>;

export function DeleteSeries(arg1:string):Promise<void>;

export function FavoriteNames(arg1:model.FavoritesQuery):Promise<Array<model.FavoriteName>>;

export function Favorites(arg1:model.FavoritesQuery):Promise<model.FavoritesResult>;

export function FileNamePlaceholders():Promise<Array<string>>;

export function FindSyncDevices():Promise<Array<devsync.Found>>;

export function Gallery(arg1:string):Promise<model.GalleryDetail>;

export function GetSettings():Promise<model.Settings>;

export function History():Promise<Array<model.HistoryEntry>>;

export function InstallUpdate():Promise<void>;

export function IsBookmarked(arg1:string):Promise<boolean>;

export function List(arg1:model.ListQuery):Promise<model.ListResult>;

export function LocalIcons():Promise<Array<main.IconFile>>;

export function MoveLocalDir(arg1:number,arg2:number):Promise<void>;

export function OpenAttachment(arg1:string,arg2:number):Promise<void>;

export function OpenExternal(arg1:string):Promise<void>;

export function OpenFolder(arg1:string):Promise<void>;

export function OpenIconsFolder():Promise<void>;

export function OwnerSettings(arg1:string,arg2:string):Promise<Record<string, string>>;

export function PairSyncDevice(arg1:string,arg2:string):Promise<void>;

export function PauseDownload(arg1:string):Promise<void>;

export function Platform():Promise<string>;

export function Plugins():Promise<Array<main.PluginInfo>>;

export function PreviewFileName(arg1:string,arg2:string,arg3:string):Promise<string>;

export function RemoveBookmark(arg1:string):Promise<void>;

export function RemoveFromLibrary(arg1:string):Promise<void>;

export function RemoveFromSeries(arg1:string):Promise<void>;

export function RemoveHistory(arg1:string):Promise<void>;

export function RemoveLocalDir(arg1:number):Promise<void>;

export function RemoveSyncDevice(arg1:string):Promise<void>;

export function RenameSeries(arg1:string,arg2:string):Promise<model.Series>;

export function RenameTag(arg1:string,arg2:string):Promise<number>;

export function ReorderSeries(arg1:string,arg2:Array<string>):Promise<model.Series>;

export function ResolveCreator(arg1:string):Promise<model.Bookmark>;

export function RestartApp():Promise<void>;

export function RestoreIgnoredArchives():Promise<number>;

export function ScanLibrary():Promise<number>;

export function SearchCreatorCandidates(arg1:string):Promise<Array<model.CreatorCandidate>>;

export function SeriesList():Promise<Array<model.Series>>;

export function SetBookmarkTags(arg1:string,arg2:Array<string>):Promise<model.Bookmark>;

export function SetBookmarkTitle(arg1:string,arg2:string):Promise<model.Bookmark>;

export function SetCreator(arg1:string,arg2:string,arg3:Array<string>,arg4:model.CreatorCandidate):Promise<model.Bookmark>;

export function SetCustomThumb(arg1:string,arg2:model.ThumbSpec,arg3:string):Promise<model.Bookmark>;

export function SetFullscreen(arg1:boolean):Promise<void>;

export function SetLocalDir(arg1:number,arg2:string,arg3:string):Promise<void>;

export function SetOwnerSetting(arg1:string,arg2:string,arg3:string,arg4:string):Promise<Record<string, string>>;

export function SetRangeTags(arg1:string,arg2:Array<string>,arg3:Array<string>):Promise<model.Bookmark>;

export function SetSettings(arg1:model.Settings):Promise<model.Settings>;

export function SetSyncDeviceName(arg1:string):Promise<void>;

export function SiteLogin(arg1:string,arg2:string,arg3:boolean):Promise<Record<string, string>>;

export function SiteStatus(arg1:string):Promise<Array<model.StatusLine>>;

export function Sites():Promise<Array<model.SiteInfo>>;

export function StartDownload(arg1:string):Promise<void>;

export function StartSyncPairing():Promise<devsync.PairingStatus>;

export function StopSyncPairing():Promise<void>;

export function Suggest(arg1:string,arg2:string):Promise<Array<model.Suggestion>>;

export function SyncNow():Promise<Array<devsync.SyncResult>>;

export function SyncStatus():Promise<devsync.Status>;

export function TagNamesJa():Promise<Record<string, string>>;

export function ToggleFullscreen():Promise<boolean>;

export function UILanguage():Promise<string>;

export function UnlinkCreatorSource(arg1:string):Promise<model.Bookmark>;

export function UpdateTags(arg1:Array<string>,arg2:Array<string>,arg3:Array<string>):Promise<void>;

export function VerifyDownloads():Promise<void>;

export function ViewAction(arg1:string,arg2:string,arg3:string,arg4:string):Promise<model.Text>;

export function ViewHeader(arg1:string,arg2:string,arg3:string):Promise<model.ViewHeader>;

export function WebURL(arg1:string):Promise<string>;

export function WindowClose():Promise<void>;

export function WindowMinimise():Promise<void>;

export function WindowToggleMaximise():Promise<void>;
