// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddBookmark(arg1) {
  return window['go']['main']['App']['AddBookmark'](arg1);
}

export function AddBookmarkFromURL(arg1) {
  return window['go']['main']['App']['AddBookmarkFromURL'](arg1);
}

export function AddHistory(arg1, arg2) {
  return window['go']['main']['App']['AddHistory'](arg1, arg2);
}

export function AddLocalDir(arg1) {
  return window['go']['main']['App']['AddLocalDir'](arg1);
}

export function AddToSeries(arg1, arg2) {
  return window['go']['main']['App']['AddToSeries'](arg1, arg2);
}

export function AppVersion() {
  return window['go']['main']['App']['AppVersion']();
}

export function ApplyFileNameFormat() {
  return window['go']['main']['App']['ApplyFileNameFormat']();
}

export function BookmarkRange(arg1) {
  return window['go']['main']['App']['BookmarkRange'](arg1);
}

export function Bookmarks() {
  return window['go']['main']['App']['Bookmarks']();
}

export function CancelViewerLoads(arg1) {
  return window['go']['main']['App']['CancelViewerLoads'](arg1);
}

export function CandidateFromURL(arg1) {
  return window['go']['main']['App']['CandidateFromURL'](arg1);
}

export function CheckUpdate() {
  return window['go']['main']['App']['CheckUpdate']();
}

export function ChooseSiteDir(arg1, arg2) {
  return window['go']['main']['App']['ChooseSiteDir'](arg1, arg2);
}

export function ClearCustomThumb(arg1) {
  return window['go']['main']['App']['ClearCustomThumb'](arg1);
}

export function ClearHistory() {
  return window['go']['main']['App']['ClearHistory']();
}

export function ClipboardText() {
  return window['go']['main']['App']['ClipboardText']();
}

export function CreateSeries(arg1, arg2) {
  return window['go']['main']['App']['CreateSeries'](arg1, arg2);
}

export function DeleteDownload(arg1) {
  return window['go']['main']['App']['DeleteDownload'](arg1);
}

export function DeleteSeries(arg1) {
  return window['go']['main']['App']['DeleteSeries'](arg1);
}

export function FavoriteNames(arg1) {
  return window['go']['main']['App']['FavoriteNames'](arg1);
}

export function Favorites(arg1) {
  return window['go']['main']['App']['Favorites'](arg1);
}

export function FileNamePlaceholders() {
  return window['go']['main']['App']['FileNamePlaceholders']();
}

export function Gallery(arg1) {
  return window['go']['main']['App']['Gallery'](arg1);
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function History() {
  return window['go']['main']['App']['History']();
}

export function InstallUpdate() {
  return window['go']['main']['App']['InstallUpdate']();
}

export function IsBookmarked(arg1) {
  return window['go']['main']['App']['IsBookmarked'](arg1);
}

export function List(arg1) {
  return window['go']['main']['App']['List'](arg1);
}

export function LocalIcons() {
  return window['go']['main']['App']['LocalIcons']();
}

export function MoveLocalDir(arg1, arg2) {
  return window['go']['main']['App']['MoveLocalDir'](arg1, arg2);
}

export function OpenAttachment(arg1, arg2) {
  return window['go']['main']['App']['OpenAttachment'](arg1, arg2);
}

export function OpenExternal(arg1) {
  return window['go']['main']['App']['OpenExternal'](arg1);
}

export function OpenFolder(arg1) {
  return window['go']['main']['App']['OpenFolder'](arg1);
}

export function OpenIconsFolder() {
  return window['go']['main']['App']['OpenIconsFolder']();
}

export function OwnerSettings(arg1, arg2) {
  return window['go']['main']['App']['OwnerSettings'](arg1, arg2);
}

export function PauseDownload(arg1) {
  return window['go']['main']['App']['PauseDownload'](arg1);
}

export function Platform() {
  return window['go']['main']['App']['Platform']();
}

export function Plugins() {
  return window['go']['main']['App']['Plugins']();
}

export function PreviewFileName(arg1, arg2, arg3) {
  return window['go']['main']['App']['PreviewFileName'](arg1, arg2, arg3);
}

export function RemoveBookmark(arg1) {
  return window['go']['main']['App']['RemoveBookmark'](arg1);
}

export function RemoveFromLibrary(arg1) {
  return window['go']['main']['App']['RemoveFromLibrary'](arg1);
}

export function RemoveFromSeries(arg1) {
  return window['go']['main']['App']['RemoveFromSeries'](arg1);
}

export function RemoveHistory(arg1) {
  return window['go']['main']['App']['RemoveHistory'](arg1);
}

export function RemoveLocalDir(arg1) {
  return window['go']['main']['App']['RemoveLocalDir'](arg1);
}

export function RenameSeries(arg1, arg2) {
  return window['go']['main']['App']['RenameSeries'](arg1, arg2);
}

export function RenameTag(arg1, arg2) {
  return window['go']['main']['App']['RenameTag'](arg1, arg2);
}

export function ReorderSeries(arg1, arg2) {
  return window['go']['main']['App']['ReorderSeries'](arg1, arg2);
}

export function ResolveCreator(arg1) {
  return window['go']['main']['App']['ResolveCreator'](arg1);
}

export function RestoreIgnoredArchives() {
  return window['go']['main']['App']['RestoreIgnoredArchives']();
}

export function ScanLibrary() {
  return window['go']['main']['App']['ScanLibrary']();
}

export function SearchCreatorCandidates(arg1) {
  return window['go']['main']['App']['SearchCreatorCandidates'](arg1);
}

export function SeriesList() {
  return window['go']['main']['App']['SeriesList']();
}

export function SetBookmarkTags(arg1, arg2) {
  return window['go']['main']['App']['SetBookmarkTags'](arg1, arg2);
}

export function SetBookmarkTitle(arg1, arg2) {
  return window['go']['main']['App']['SetBookmarkTitle'](arg1, arg2);
}

export function SetCreator(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['SetCreator'](arg1, arg2, arg3, arg4);
}

export function SetCustomThumb(arg1, arg2, arg3) {
  return window['go']['main']['App']['SetCustomThumb'](arg1, arg2, arg3);
}

export function SetFullscreen(arg1) {
  return window['go']['main']['App']['SetFullscreen'](arg1);
}

export function SetLocalDir(arg1, arg2, arg3) {
  return window['go']['main']['App']['SetLocalDir'](arg1, arg2, arg3);
}

export function SetOwnerSetting(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['SetOwnerSetting'](arg1, arg2, arg3, arg4);
}

export function SetRangeTags(arg1, arg2, arg3) {
  return window['go']['main']['App']['SetRangeTags'](arg1, arg2, arg3);
}

export function SetSettings(arg1) {
  return window['go']['main']['App']['SetSettings'](arg1);
}

export function SiteLogin(arg1, arg2, arg3) {
  return window['go']['main']['App']['SiteLogin'](arg1, arg2, arg3);
}

export function SiteStatus(arg1) {
  return window['go']['main']['App']['SiteStatus'](arg1);
}

export function Sites() {
  return window['go']['main']['App']['Sites']();
}

export function StartDownload(arg1) {
  return window['go']['main']['App']['StartDownload'](arg1);
}

export function Suggest(arg1, arg2) {
  return window['go']['main']['App']['Suggest'](arg1, arg2);
}

export function TagNamesJa() {
  return window['go']['main']['App']['TagNamesJa']();
}

export function ToggleFullscreen() {
  return window['go']['main']['App']['ToggleFullscreen']();
}

export function UILanguage() {
  return window['go']['main']['App']['UILanguage']();
}

export function UnlinkCreatorSource(arg1) {
  return window['go']['main']['App']['UnlinkCreatorSource'](arg1);
}

export function UpdateTags(arg1, arg2, arg3) {
  return window['go']['main']['App']['UpdateTags'](arg1, arg2, arg3);
}

export function VerifyDownloads() {
  return window['go']['main']['App']['VerifyDownloads']();
}

export function ViewAction(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['ViewAction'](arg1, arg2, arg3, arg4);
}

export function ViewHeader(arg1, arg2, arg3) {
  return window['go']['main']['App']['ViewHeader'](arg1, arg2, arg3);
}

export function WebURL(arg1) {
  return window['go']['main']['App']['WebURL'](arg1);
}

export function WindowClose() {
  return window['go']['main']['App']['WindowClose']();
}

export function WindowMinimise() {
  return window['go']['main']['App']['WindowMinimise']();
}

export function WindowToggleMaximise() {
  return window['go']['main']['App']['WindowToggleMaximise']();
}
