// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {model} from '../models';
import {update} from '../models';

export function AddBookmark(arg1:model.GallerySummary):Promise<model.Bookmark>;

export function AddHistory(arg1:model.GallerySummary,arg2:string):Promise<void>;

export function AddToSeries(arg1:string,arg2:Array<string>):Promise<model.Series>;

export function AppVersion():Promise<string>;

export function ApplyFileNameFormat():Promise<number>;

export function BookmarkRange(arg1:model.RangeRequest):Promise<model.Bookmark>;

export function Bookmarks():Promise<Array<model.Bookmark>>;

export function CancelViewerLoads(arg1:string):Promise<void>;

export function CandidateFromURL(arg1:string):Promise<model.CreatorCandidate>;

export function CheckUpdate():Promise<update.Release>;

export function ChooseLibraryDir(arg1:string):Promise<string>;

export function ClearCustomThumb(arg1:string):Promise<model.Bookmark>;

export function ClearHistory():Promise<void>;

export function CreateSeries(arg1:string,arg2:Array<string>):Promise<model.Series>;

export function DeleteDownload(arg1:string):Promise<void>;

export function DeleteSeries(arg1:string):Promise<void>;

export function Favorites(arg1:model.FavoritesQuery):Promise<model.FavoritesResult>;

export function FileNamePlaceholders():Promise<Array<string>>;

export function Gallery(arg1:string):Promise<model.GalleryDetail>;

export function GetSettings():Promise<model.Settings>;

export function History():Promise<Array<model.HistoryEntry>>;

export function InstallUpdate():Promise<void>;

export function IsBookmarked(arg1:string):Promise<boolean>;

export function List(arg1:model.ListQuery):Promise<model.ListResult>;

export function OpenExternal(arg1:string):Promise<void>;

export function OpenFolder(arg1:string):Promise<void>;

export function PauseDownload(arg1:string):Promise<void>;

export function PreviewFileName(arg1:string,arg2:string):Promise<string>;

export function RemoveBookmark(arg1:string):Promise<void>;

export function RemoveFromSeries(arg1:string):Promise<void>;

export function RemoveHistory(arg1:string):Promise<void>;

export function RenameSeries(arg1:string,arg2:string):Promise<model.Series>;

export function RenameTag(arg1:string,arg2:string):Promise<number>;

export function ReorderSeries(arg1:string,arg2:Array<string>):Promise<model.Series>;

export function ResolveCreator(arg1:string):Promise<model.Bookmark>;

export function RestoreIgnoredArchives():Promise<number>;

export function ScanLibrary():Promise<number>;

export function SearchCreatorCandidates(arg1:string):Promise<Array<model.CreatorCandidate>>;

export function SeriesList():Promise<Array<model.Series>>;

export function SetBookmarkTags(arg1:string,arg2:Array<string>):Promise<model.Bookmark>;

export function SetBookmarkTitle(arg1:string,arg2:string):Promise<model.Bookmark>;

export function SetCreator(arg1:string,arg2:string,arg3:Array<string>,arg4:model.CreatorCandidate):Promise<model.Bookmark>;

export function SetCustomThumb(arg1:string,arg2:model.ThumbSpec,arg3:string):Promise<model.Bookmark>;

export function SetFullscreen(arg1:boolean):Promise<void>;

export function SetRangeTags(arg1:string,arg2:Array<string>,arg3:Array<string>):Promise<model.Bookmark>;

export function SetSettings(arg1:model.Settings):Promise<model.Settings>;

export function Sites():Promise<Array<model.SiteInfo>>;

export function StartDownload(arg1:string):Promise<void>;

export function Suggest(arg1:string):Promise<Array<model.Suggestion>>;

export function ToggleFullscreen():Promise<boolean>;

export function UILanguage():Promise<string>;

export function UnlinkCreatorSource(arg1:string):Promise<model.Bookmark>;

export function UpdateTags(arg1:Array<string>,arg2:Array<string>,arg3:Array<string>):Promise<void>;

export function VerifyDownloads():Promise<void>;

export function WebURL(arg1:string):Promise<string>;

export function WindowClose():Promise<void>;

export function WindowMinimise():Promise<void>;

export function WindowToggleMaximise():Promise<void>;
